
development:
  adapter: postgresql
  database: stori
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: stori_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: stori_prod
  pool: 5
  timeout: 5000

